[9.0][FIX][web_export_view] ReferenceError: instance is not defined
There was a bug that could be easily reproduced by:

1. Go to *Sales > Products*.
2. Choose list view.
3. Select all.
4. *Export current view > Excel*.

It raised this message to the user:

    ReferenceError: instance is not defined

This is all due to a wrong migration from v8 code. `instance` exists no more in
v9, instead we need to use some methods and variables from correct modules.